apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-ywwfxpdq
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/quay_xjiang/go-ywwfxpdq:36fd621c39ec90f6b76354609508690b147ac58a@sha256:7165929ffb0e78c1b2824c85918b83a8f12f636dd1068442a0a2cd3f749b8dd9
          name: container-image
